### ISSUE TITLE
Error occuring when connect a metamask wallet

### ISSUE THREAD

**Issue by LinuxKunaL** [ac12644/NFT-Marketplace#11]
**Issue Description:**

When using the application on a testnet network, the entire app crashes. This issue arises due to the absence of proper handling for network changes, especially when switching from testnet to mainnet.

![Screenshot from 2023-12-07 13-08-24](https://github.com/ac12644/NFT-Marketplace/assets/75113218/a225cc84-18c2-4c72-b281-2e900aeded34)

**Proposed Solution:**

To address this problem, we suggest implementing a toast message that prompts users to confirm their intention to switch the network. This will serve as a preventive measure, helping users avoid unintentional network changes that could lead to app crashes.

_Can i make PR for this issue_

**Comment by ac12644** [comment]
You can make PR. Thanks
