### ISSUE TITLE
AxiosError: Request failed with status code 400

### ISSUE THREAD

**Issue by ubuntupunk** [ac12644/NFT-Marketplace#3]
Running site throws up this Unhandled Runtime Error: `AxiosError: Request failed with status code 400`

**Comment by ac12644** [comment]
This was because INFURA has deprecated the public ipfs gateway link i.e,https://ipfs.infura.io/ipfs resulting unable to fetch image from URL. But I have updated the repo now. Thank you for pointing error

**Comment by ubuntupunk** [comment]
Shouldn't that be a const from the .env like INFURA_IPFS_GATEWAY= ?

**Comment by ac12644** [comment]
during transaction defined url is hardcoded on chain. Also tried with cid but public domain is no longer working. If you find any solution please let me know or create pull request :)

**Comment by ubuntupunk** [comment]
Not sure how one would bypass a previous hardcoded address. Is there any way to avoid infura, option to use other cloud providers like [https://www.pinata.cloud?](https://www.pinata.cloud?)

**Comment by ac12644** [comment]
for pinata:

```Javascript

    const url =  `https://api.pinata.cloud/pinning/pinFileToIPFS`

    const response = await axios.post(
      url,
      formData,
      {
          maxContentLength: "Infinity",
          headers: {
              "Content-Type": `multipart/form-data;boundary=${FILE_DATA._boundary}`, 
              'pinata_api_key': API_KEY,
              'pinata_secret_api_key': API_SECRET_KEY
          }
      }
  )
console.log(response)
const hash = response.data.IpfsHash;

```
