### ISSUE TITLE
yarn run dev is not working

### ISSUE THREAD

**Issue by asadazizfreelancer** [ac12644/NFT-Marketplace#4]

**Comment by ac12644** [comment]
try to add env variables and then run.

**Comment by asadazizfreelancer** [comment]
Now it's working but I'm facing one issue when i tried to list nft again on marketplace the error occurs

Buttonfunc is not a function

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ac12644** [comment]
the error might be in proptypes which component is it?

**Comment by asadazizfreelancer** [comment]
Yes from PortfolioGrid component

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ac12644** [comment]
I have updated some parts try with that

**Comment by asadazizfreelancer** [comment]
Kindly can you explain your project
The use of docker?


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ac12644** [comment]
not needed I removed it yesterday

**Comment by asadazizfreelancer** [comment]
Ok
Explain the project kindly

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ac12644** [comment]
what do you want to know?

**Comment by asadazizfreelancer** [comment]
why my created nfts are gone when i re start the project

**Comment by ac12644** [comment]
are you getting any errors in the console share screenshot?

**Comment by asadazizfreelancer** [comment]
Hi the network is down now I am facing this error

  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'

while deploying the hardhat

**Comment by ac12644** [comment]
use alchemy mumbai RPC

**Comment by asadazizfreelancer** [comment]
what about the gas fee ?

**Comment by asadazizfreelancer** [comment]
gas fee on marketplace is auto or you adjust by own?

**Comment by ac12644** [comment]
It's auto

**Comment by asadazizfreelancer** [comment]
ok how they calculate the fee?

**Comment by ac12644** [comment]
https://support.polygonscan.com/support/solutions/articles/69000793833-what-is-gas-fee-%E2%9B%BD

**Comment by asadazizfreelancer** [comment]
The is again there :(
butnFunction is not a function

**Comment by asadazizfreelancer** [comment]
Are you using a pre-built Material UI theme?

**Comment by asadazizfreelancer** [comment]
and what is the Function of Firebase in the project?

**Comment by ac12644** [comment]
for newsletter
