### ISSUE TITLE
TypeError: buttonFunc is not a function

### ISSUE THREAD

**Issue by newherointown** [ac12644/NFT-Marketplace#6]
![Screenshot 2022-12-18 151410](https://user-images.githubusercontent.com/120913946/208292588-6aff05ae-fd95-419d-9777-76f5a8178cd7.png)

I am facing this error while again listing the NFTs

**Comment by kuntumseroja** [comment]
same happened here, any clue?

**Comment by ac12644** [comment]
Please pull the latest commit. I have made some updates to the code.
